import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading, mutate } = trpc.transactions.initiate.useMutation();

  const createTransaction = async () => {
    await mutate({
      network: "DEVNET",
      toPublicKey: "ArHNuuRHFtURYMPybV1iXjG47RXqBsLpPaWScyT6mknt",
      mint: "Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr",
      amount: 4.20691,
      apiKey: "cl84qr9tx0000i0ilzcb2rzxw",
    });
  };

  useEffect(() => {
    if (!data && !isLoading) {
      createTransaction();
    }
  }, []);

  useEffect(() => {
    if (data) {
      window.location.href = data.url;
    }
  }, [data]);

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
